# Generated by Django 4.1.5 on 2023-01-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('centro', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('instagram', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joind', models.DateTimeField(auto_now_add=True)),
                ('last_joind', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
