# Generated by Django 4.1.5 on 2023-01-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='medicos/imagenes'),
        ),
    ]
