# Generated by Django 4.1.5 on 2023-02-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0003_medicos_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
