# Generated by Django 4.1.5 on 2023-02-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0004_medicos_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicos',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='nombres',
        ),
        migrations.AddField(
            model_name='medicos',
            name='nombres_completo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
