# Generated by Django 4.1.5 on 2023-01-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Centros', '0002_ciudad_tipo_prestado_provincia_alter_centros_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centros',
            name='provincia',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
