# Generated by Django 4.1.5 on 2023-02-08 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Planes', '0003_alter_planes_proceio'),
    ]

    operations = [
        migrations.CreateModel(
            name='afiliados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nss', models.IntegerField(max_length=15, unique=True)),
                ('Poliza', models.CharField(max_length=17, unique=True)),
                ('Nombre_del_Afiliado', models.CharField(max_length=200)),
                ('Cedula', models.CharField(max_length=200, unique=True)),
                ('Fecha_Nacimiento', models.DateField(blank=True, max_length=14, null=True)),
                ('Estado_Civil', models.CharField(choices=[('1', 'Soltero'), ('2', 'Casado')], default='1', max_length=50)),
                ('Parentesco', models.CharField(choices=[('1', 'TITULAR'), ('2', 'ESPOSA'), ('3', 'HIJA'), ('4', 'MADRE'), ('5', 'HIJO'), ('6', 'ESPOSO'), ('7', 'HIJASTRA'), ('8', 'COMPAÑERO DE VIDA'), ('9', 'PADRE'), ('10', 'HIJASTRO'), ('11', 'SOBRINA'), ('12', 'HIJA - TITULAR'), ('13', 'HIJO - TITULAR'), ('14', 'HERMANA'), ('15', 'NIETA')], default='1', max_length=25)),
                ('Sexo', models.CharField(choices=[('1', 'MASCULINO'), ('2', 'FEMENINO')], default='1', max_length=25)),
                ('Estado', models.CharField(choices=[('1', 'ACTIVO'), ('2', 'CANCELADO'), ('3', 'INACTIVO POR FALTA DE PAGO'), ('4', 'EXCLUIDO POR FALLECIMIENTO'), ('5', 'AFILIACION AUTOMATICA'), ('6', 'PDSS PENDIENTE DE DISPERSION'), ('7', 'CANCELADO POR TRASPASO'), ('8', 'EN PROCESO'), ('9', 'EN OTRA ARS'), ('10', 'RETIRADO, MAYORIA EDAD'), ('11', 'OTRA POLIZA ASIGNADA'), ('12', 'CXC VOLUNTARIOS'), ('14', 'PENDIENTE UNIPAGO'), ('15', 'ERROR UNIPAGO'), ('16', 'ERROR AL VALIDAR'), ('17', 'ERROR AL DIGITAR')], default='1', max_length=25)),
                ('Telefono', models.CharField(blank=True, max_length=17, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=400, null=True)),
                ('Complementario', models.BooleanField(default=False)),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planes.planes')),
            ],
        ),
    ]
