# Generated by Django 4.1.5 on 2023-02-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Afiliados', '0002_alter_afiliados_nss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliados',
            name='Cedula',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='afiliados',
            name='Estado',
            field=models.CharField(blank=True, choices=[('1', 'ACTIVO'), ('2', 'CANCELADO'), ('3', 'INACTIVO POR FALTA DE PAGO'), ('4', 'EXCLUIDO POR FALLECIMIENTO'), ('5', 'AFILIACION AUTOMATICA'), ('6', 'PDSS PENDIENTE DE DISPERSION'), ('7', 'CANCELADO POR TRASPASO'), ('8', 'EN PROCESO'), ('9', 'EN OTRA ARS'), ('10', 'RETIRADO, MAYORIA EDAD'), ('11', 'OTRA POLIZA ASIGNADA'), ('12', 'CXC VOLUNTARIOS'), ('14', 'PENDIENTE UNIPAGO'), ('15', 'ERROR UNIPAGO'), ('16', 'ERROR AL VALIDAR'), ('17', 'ERROR AL DIGITAR')], default='1', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='afiliados',
            name='Estado_Civil',
            field=models.CharField(blank=True, choices=[('1', 'Soltero'), ('2', 'Casado')], default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='afiliados',
            name='Nombre_del_Afiliado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='afiliados',
            name='Nss',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='afiliados',
            name='Parentesco',
            field=models.CharField(blank=True, choices=[('1', 'TITULAR'), ('2', 'ESPOSA'), ('3', 'HIJA'), ('4', 'MADRE'), ('5', 'HIJO'), ('6', 'ESPOSO'), ('7', 'HIJASTRA'), ('8', 'COMPAÑERO DE VIDA'), ('9', 'PADRE'), ('10', 'HIJASTRO'), ('11', 'SOBRINA'), ('12', 'HIJA - TITULAR'), ('13', 'HIJO - TITULAR'), ('14', 'HERMANA'), ('15', 'NIETA')], default='1', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='afiliados',
            name='Poliza',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='afiliados',
            name='Sexo',
            field=models.CharField(blank=True, choices=[('1', 'MASCULINO'), ('2', 'FEMENINO')], default='1', max_length=25, null=True),
        ),
    ]
