# Generated by Django 4.1.5 on 2023-02-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Afiliados', '0003_alter_afiliados_cedula_alter_afiliados_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliados',
            name='Estado_Civil',
            field=models.CharField(blank=True, choices=[('SOLTERO(A)', 'Soltero(a)'), ('CASADO(A)', 'Casado(a)'), ('DIVORCIADO(A)', 'Divorciado(a)'), ('VIUDO(A)', 'Viudo(a)')], default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='afiliados',
            name='Parentesco',
            field=models.CharField(blank=True, choices=[('TITULAR', 'TITULAR'), ('ESPOSA', 'ESPOSA'), ('HIJA', 'HIJA'), ('MADRE', 'MADRE'), ('HIJO', 'HIJO'), ('ESPOSO', 'ESPOSO'), ('HIJASTRA', 'HIJASTRA'), ('COMPAÑERO DE VIDA', 'COMPAÑERO DE VIDA'), ('PADRE', 'PADRE'), ('HIJASTRO', 'HIJASTRO'), ('SOBRINA', 'SOBRINA'), ('HIJA - TITULAR', 'HIJA - TITULAR'), ('HIJO - TITULAR', 'HIJO - TITULAR'), ('HERMANA', 'HERMANA'), ('NIETA', 'NIETA')], default='1', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='afiliados',
            name='Sexo',
            field=models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='1', max_length=25, null=True),
        ),
    ]
